const STASK = {
  ADD: "ADD",
  DELETE: "DELETE",
  DELETE_ALL: "DELETE_ALL",
  TICK_COMPLETE: "TICK_COMPLETE",
  TICK_ALL: "TICK_ALL",
  // REMOVE_COMPLETE: 'REMOVE_COMPLETE',
  GET_STASK: "GET_STASK",
  GET_STASK_IN_PROCCESS: "GET_STASK_IN_PROCCESS",
  GET_STASK_ERROR: "GET_STASK_ERROR",
  UPDATE_STASK: "UPDATE_STASK",
};

export default STASK;
